<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Review;
use DB;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reviews')->truncate();

        $reviews = [
            [
                'beer_id' => 1,
                'user_id' => 1,
                'review' => "I really enjoyed this, very much looking forward to my next glass",
                'rating' => 4,
                'favorite' => false,
                'body' => 5,
                'linger' => 3,
                'herbal' => 1,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 4,
                'sour' => 2
            ], [
                'beer_id' => 1,
                'user_id' => 2,
                'review' => "I felt as though I had been elevated to another, higher plain of consciousness after drinking this amazing brew!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 1,
                'user_id' => 3,
                'review' => "Excellent taste, as well as excellent presentation",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 2,
                'user_id' => 1,
                'review' => "I found this quite refreshing.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 2,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 2,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 3,
                'user_id' => 1,
                'review' => "An interesting experience. I'm eager to try it again.",
                'rating' => 4,
                'favorite' => false,
                'body' => 5,
                'linger' => 3,
                'herbal' => 1,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 4,
                'sour' => 2
            ], [
                'beer_id' => 3,
                'user_id' => 2,
                'review' => "Another, please, sir!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 3,
                'user_id' => 3,
                'review' => "Definitely a new favourite!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 4,
                'user_id' => 1,
                'review' => "Nice enough. I'd be happy to have it again.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 4,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 4,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 5,
                'user_id' => 1,
                'review' => "This was a very tasty beer, looking forward to another glass.",
                'rating' => 4,
                'favorite' => false,
                'body' => 5,
                'linger' => 3,
                'herbal' => 1,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 4,
                'sour' => 2
            ], [
                'beer_id' => 5,
                'user_id' => 2,
                'review' => "I felt as though I had been elevated to another, higher plain of consciousness after drinking this amazing brew!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 5,
                'user_id' => 3,
                'review' => "Nice beer, and good presentation.",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 6,
                'user_id' => 1,
                'review' => "An enjoyable drink... a nice end to a hard day at work.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 6,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 6,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 7,
                'user_id' => 1,
                'review' => "Ok, but would be happy to drink this again.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 7,
                'user_id' => 2,
                'review' => "I wasn't sure when I ordered this, but no regrets.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 7,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 8,
                'user_id' => 1,
                'review' => "Fairy good beer.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 8,
                'user_id' => 2,
                'review' => "This was the highlight of my beer tasting trip last weekend.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 8,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 9,
                'user_id' => 1,
                'review' => "Yum yum.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 9,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 9,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 10,
                'user_id' => 1,
                'review' => "Tasty stuff.... more please!",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 10,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 10,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 11,
                'user_id' => 1,
                'review' => "This was a very tasty beer, shame about the price.",
                'rating' => 4,
                'favorite' => false,
                'body' => 5,
                'linger' => 3,
                'herbal' => 1,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 4,
                'sour' => 2
            ], [
                'beer_id' => 11,
                'user_id' => 2,
                'review' => "I felt as though I had been elevated to another, higher plain of consciousness after drinking this amazing brew!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 11,
                'user_id' => 3,
                'review' => "I felt as though I had been elevated to another, higher plain of consciousness after drinking this amazing brew!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 12,
                'user_id' => 1,
                'review' => "Ok, that's all.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 12,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 12,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 13,
                'user_id' => 1,
                'review' => "This was a very tasty beer, shame about the price.",
                'rating' => 4,
                'favorite' => false,
                'body' => 5,
                'linger' => 3,
                'herbal' => 1,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 4,
                'sour' => 2
            ], [
                'beer_id' => 13,
                'user_id' => 2,
                'review' => "I felt as though I had been elevated to another, higher plain of consciousness after drinking this amazing brew!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 13,
                'user_id' => 3,
                'review' => "I felt as though I had been elevated to another, higher plain of consciousness after drinking this amazing brew!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 14,
                'user_id' => 1,
                'review' => "Ok, that's all.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 14,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 14,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 15,
                'user_id' => 1,
                'review' => "This was a very tasty beer, shame about the price.",
                'rating' => 4,
                'favorite' => false,
                'body' => 5,
                'linger' => 3,
                'herbal' => 1,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 4,
                'sour' => 2
            ], [
                'beer_id' => 15,
                'user_id' => 2,
                'review' => "I felt as though I had been elevated to another, higher plain of consciousness after drinking this amazing brew!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 15,
                'user_id' => 3,
                'review' => "I felt as though I had been elevated to another, higher plain of consciousness after drinking this amazing brew!",
                'rating' => 5,
                'favorite' => true,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 2,
                'bitter' => 2,
                'sour' => 2
            ], [
                'beer_id' => 16,
                'user_id' => 1,
                'review' => "Ok, that's all.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 16,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 16,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 17,
                'user_id' => 1,
                'review' => "Ok, that's all.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 17,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 17,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 18,
                'user_id' => 1,
                'review' => "Ok, that's all.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 18,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 18,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 19,
                'user_id' => 1,
                'review' => "Ok, that's all.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 19,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 19,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ], [
                'beer_id' => 20,
                'user_id' => 1,
                'review' => "Ok, that's all.",
                'rating' => 2,
                'favorite' => false,
                'body' => 3,
                'linger' => 2,
                'herbal' => 1,
                'citrus' => 1,
                'hoppy' => 3,
                'bitter' => 3,
                'sour' => 1
            ], [
                'beer_id' => 20,
                'user_id' => 2,
                'review' => "Good stuff, I could drink this for hours.",
                'rating' => 4,
                'favorite' => true,
                'body' => 3,
                'linger' => 1,
                'herbal' => 2,
                'citrus' => 2,
                'hoppy' => 4,
                'bitter' => 2,
                'sour' => 4
            ], [
                'beer_id' => 20,
                'user_id' => 3,
                'review' => "Nice colour, quite attractive looking liquid...",
                'rating' => 4,
                'favorite' => false,
                'body' => 2,
                'linger' => 2,
                'herbal' => 2,
                'citrus' => 3,
                'hoppy' => 5,
                'bitter' => 1,
                'sour' => 1
            ],

        ];

        foreach ($reviews as $reviewex) {
            $review = new Review;

            $review->beer_id = $reviewex['beer_id'];
            $review->user_id = $reviewex['user_id'];
            $review->review = $reviewex['review'];
            $review->rating = $reviewex['rating'];
            $review->favorite = $reviewex['favorite'];
            $review->body = $reviewex['body'];
            $review->linger = $reviewex['linger'];
            $review->herbal = $reviewex['herbal'];
            $review->citrus = $reviewex['citrus'];
            $review->hoppy = $reviewex['hoppy'];
            $review->bitter = $reviewex['bitter'];
            $review->sour = $reviewex['sour'];

            $review->save();
        }
    }
}
